##Google CSSI_KIR

application: college-connect
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /templates/js
  static_dir: js

- url: /templates/css
  static_dir: css

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /app-stylesheets
  static_dir: app-stylesheets

- url: /my-images
  static_dir: my-images

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
